using CS395SI_Spring2023_K4S.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CS395SI_Spring2023_Group1.Pages.Managers
{
    [Authorize(Roles = "Manager,Admin")]
    public class FacultyApplicationsModel : PageModel
    {
        private readonly CS395SI_Spring2023_Group1.Data.CS395SI_Spring2023_Group1Context _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public FacultyApplicationsModel(
            CS395SI_Spring2023_Group1.Data.CS395SI_Spring2023_Group1Context context,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public List<Spring2026_Group1_EmployeeApplication> Applications { get; set; } = new();
        public string ActiveTab { get; set; } = "Pending";
        public int PendingCount { get; set; }
        public int ApprovedCount { get; set; }
        public int DeniedCount { get; set; }

        public async Task OnGetAsync(string tab = "Pending")
        {
            ActiveTab = tab;

            // Managers only see Instructor applications
            Applications = await _context.Spring2026_Group1_EmployeeApplication
                .Where(a => a.ApplicationStatus == tab && a.DesiredPosition == "Instructor")
                .OrderBy(a => a.ApplicationDate)
                .ToListAsync();

            var all = await _context.Spring2026_Group1_EmployeeApplication
                .Where(a => a.DesiredPosition == "Instructor")
                .ToListAsync();

            PendingCount = all.Count(a => a.ApplicationStatus == "Pending");
            ApprovedCount = all.Count(a => a.ApplicationStatus == "Approved");
            DeniedCount = all.Count(a => a.ApplicationStatus == "Denied");
        }

        public async Task<IActionResult> OnPostApproveAsync(int id, string notes)
        {
            var application = await _context.Spring2026_Group1_EmployeeApplication.FindAsync(id);

            if (application == null || application.DesiredPosition != "Instructor")
            {
                TempData["ErrorMessage"] = "Invalid instructor application.";
                return RedirectToPage(new { tab = "Pending" });
            }

            var currentUser = await _userManager.GetUserAsync(User);

            application.ApplicationStatus = "Approved";
            application.ReviewedBy = currentUser?.Email;
            application.ReviewDate = DateTime.UtcNow;
            application.ReviewNotes = notes;

            // ✅ Create Instructor record
            await CreateInstructorRecordAsync(application);

            // ✅ Assign Instructor role
            await AssignRoleAsync(application.Email, "Instructor");

            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = $"{application.FullName}'s instructor application has been approved and Instructor role assigned.";
            return RedirectToPage(new { tab = "Pending" });
        }

        public async Task<IActionResult> OnPostDenyAsync(int id, string notes)
        {
            var application = await _context.Spring2026_Group1_EmployeeApplication.FindAsync(id);

            if (application == null || application.DesiredPosition != "Instructor")
            {
                TempData["ErrorMessage"] = "Invalid instructor application.";
                return RedirectToPage(new { tab = "Pending" });
            }

            var currentUser = await _userManager.GetUserAsync(User);

            application.ApplicationStatus = "Denied";
            application.ReviewedBy = currentUser?.Email;
            application.ReviewDate = DateTime.UtcNow;
            application.ReviewNotes = notes;

            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = $"{application.FullName}'s instructor application has been denied.";
            return RedirectToPage(new { tab = "Pending" });
        }

        private async Task CreateInstructorRecordAsync(Spring2026_Group1_EmployeeApplication application)
        {
            var existingInstructor = await _context.Spring2026_Group1_Instructor
                .FirstOrDefaultAsync(i => i.Email == application.Email);

            if (existingInstructor == null)
            {
                // NO manual ID generation
                var instructor = new Spring2026_Group1_Instructor
                {
                    // InstructorID NOT set - auto-generated by database
                    Email = application.Email,
                    FullName = application.FullName,
                    Speciality = application.Specialties,
                    HireDate = DateTime.UtcNow,
                    IsActive = true,
                    ApprovedDate = DateTime.UtcNow,
                    ApprovedBy = User.Identity?.Name,
                    Status = "Active"
                };
                _context.Spring2026_Group1_Instructor.Add(instructor);
                await _context.SaveChangesAsync();
            }
        }

        private async Task AssignRoleAsync(string email, string roleName)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user == null) return;

            if (!await _roleManager.RoleExistsAsync(roleName))
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName));
            }

            if (!await _userManager.IsInRoleAsync(user, roleName))
            {
                await _userManager.AddToRoleAsync(user, roleName);
            }
        }
    }
}